In [1]:
import pandas as pd

In [2]:
df_distance = pd.read_csv('datalab/eleme_round1_train_20200313/distance/distance_20200201.txt')

In [3]:
df_distance.head()

,courier_id,wave_index,tracking_id,source_type,source_lng,source_lat,target_tracking_id,target_type,target_lng,target_lat,grid_distance
0,100002543,0,2100074536706869066,ASSIGN,121.641337,39.141340,2100074542836254538,ASSIGN,121.635755,39.141497,542.0
1,100002543,0,2100074542836254538,PICKUP,121.647214,39.135549,2100074542836254538,ASSIGN,121.635755,39.141497,2042.0
2,100002543,0,2100074542836254538,DELIVERY,121.647324,39.126481,2100074542836254538,ASSIGN,121.635755,39.141497,3343.0
3,100002543,0,2100074536706869066,PICKUP,121.647214,39.135549,2100074542836254538,ASSIGN,121.635755,39.141497,2042.0
4,100002543,0,2100074536706869066,DELIVERY,121.655694,39.123121,2100074542836254538,ASSIGN,121.635755,39.141497,3945.0